// Generated by gencpp from file demo_action/addResult.msg
// DO NOT EDIT!


#ifndef DEMO_ACTION_MESSAGE_ADDRESULT_H
#define DEMO_ACTION_MESSAGE_ADDRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_action
{
template <class ContainerAllocator>
struct addResult_
{
  typedef addResult_<ContainerAllocator> Type;

  addResult_()
    : result(0)  {
    }
  addResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::demo_action::addResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_action::addResult_<ContainerAllocator> const> ConstPtr;

}; // struct addResult_

typedef ::demo_action::addResult_<std::allocator<void> > addResult;

typedef boost::shared_ptr< ::demo_action::addResult > addResultPtr;
typedef boost::shared_ptr< ::demo_action::addResult const> addResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_action::addResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_action::addResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_action::addResult_<ContainerAllocator1> & lhs, const ::demo_action::addResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_action::addResult_<ContainerAllocator1> & lhs, const ::demo_action::addResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::demo_action::addResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_action::addResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action::addResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action::addResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action::addResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action::addResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_action::addResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::demo_action::addResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_action::addResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_action/addResult";
  }

  static const char* value(const ::demo_action::addResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_action::addResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#最终结果\n"
"int32 result\n"
;
  }

  static const char* value(const ::demo_action::addResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_action::addResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_action::addResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_action::addResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_ACTION_MESSAGE_ADDRESULT_H
